/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as BrdRouteImport } from './routes/brd'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as DashIndexRouteImport } from './routes/_dash.index'
import { Route as DashArchivedRouteImport } from './routes/_dash.archived'
import { Route as DashDashboardRouteImport } from './routes/_dash.dashboard'
import { Route as DashEmailsRouteImport } from './routes/_dash.emails'
import { Route as DashGoLiveRouteImport } from './routes/_dash.go-live'
import { Route as DashPlatformsRouteImport } from './routes/_dash.platforms'
import { Route as DashRisksRouteImport } from './routes/_dash.risks'
import { Route as DashShopifyLtEmailsRouteImport } from './routes/_dash.shopify-lt-emails'
import { Route as DashShopifySmeRouteImport } from './routes/_dash.shopify-sme'
import { Route as DashTenantsRouteImport } from './routes/_dash.tenants'
import { Route as PortalMidRouteImport } from './routes/portal.$mid'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as DashProjectsGoLiveRouteImport } from './routes/_dash.projects.go-live'
import { Route as DashProjectsKanbanRouteImport } from './routes/_dash.projects.kanban'
import { Route as DashProjectsListRouteImport } from './routes/_dash.projects.list'
import { Route as DashReportsSubTabRouteImport } from './routes/_dash.reports.$subTab'
import { Route as DashSettingsSubTabRouteImport } from './routes/_dash.settings.$subTab'
import { Route as ApiPublicAiActionsRouteImport } from './routes/api/public/ai-actions'
import { Route as ApiPublicAiChatRouteImport } from './routes/api/public/ai-chat'
import { Route as ApiPublicAiFieldMappingRouteImport } from './routes/api/public/ai-field-mapping'
import { Route as ApiPublicAiProjectInsightsRouteImport } from './routes/api/public/ai-project-insights'
import { Route as ApiPublicApiKeysRouteImport } from './routes/api/public/api-keys'
import { Route as ApiPublicAssignShopifySmeOwnerRouteImport } from './routes/api/public/assign-shopify-sme-owner'
import { Route as ApiPublicBackfillShopifySmeAssignmentsRouteImport } from './routes/api/public/backfill-shopify-sme-assignments'
import { Route as ApiPublicBrdFormApiRouteImport } from './routes/api/public/brd-form-api'
import { Route as ApiPublicCheckOverdueTasksRouteImport } from './routes/api/public/check-overdue-tasks'
import { Route as ApiPublicCreateJiraTicketRouteImport } from './routes/api/public/create-jira-ticket'
import { Route as ApiPublicCreateUserRouteImport } from './routes/api/public/create-user'
import { Route as ApiPublicCronRouteImport } from './routes/api/public/cron'
import { Route as ApiPublicDeleteUserRouteImport } from './routes/api/public/delete-user'
import { Route as ApiPublicEnrichGoliveTrackerRouteImport } from './routes/api/public/enrich-golive-tracker'
import { Route as ApiPublicFetchProjectEmailsRouteImport } from './routes/api/public/fetch-project-emails'
import { Route as ApiPublicFetchProjectJiraTicketsRouteImport } from './routes/api/public/fetch-project-jira-tickets'
import { Route as ApiPublicGetProjectLinksRouteImport } from './routes/api/public/get-project-links'
import { Route as ApiPublicJiraCreateUrlRouteImport } from './routes/api/public/jira-create-url'
import { Route as ApiPublicKwikassistAiChatRouteImport } from './routes/api/public/kwikassist-ai-chat'
import { Route as ApiPublicMerchantPortalDataRouteImport } from './routes/api/public/merchant-portal-data'
import { Route as ApiPublicPollEmailsRouteImport } from './routes/api/public/poll-emails'
import { Route as ApiPublicPollPlatformGoliveEmailsRouteImport } from './routes/api/public/poll-platform-golive-emails'
import { Route as ApiPublicPollShopifySmeEmailsRouteImport } from './routes/api/public/poll-shopify-sme-emails'
import { Route as ApiPublicSandboxTestRouteImport } from './routes/api/public/sandbox-test'
import { Route as ApiPublicSendMovementReportRouteImport } from './routes/api/public/send-movement-report'
import { Route as ApiPublicSendNotificationRouteImport } from './routes/api/public/send-notification'
import { Route as ApiPublicSendPlatformWelcomeRouteImport } from './routes/api/public/send-platform-welcome'
import { Route as ApiPublicSendScheduledMovementReportRouteImport } from './routes/api/public/send-scheduled-movement-report'
import { Route as ApiPublicSendScheduledReportRouteImport } from './routes/api/public/send-scheduled-report'
import { Route as ApiPublicSendScheduledTatReportRouteImport } from './routes/api/public/send-scheduled-tat-report'
import { Route as ApiPublicSetPasswordRouteImport } from './routes/api/public/set-password'
import { Route as ApiPublicShopifyLtEmailCommsRouteImport } from './routes/api/public/shopify-lt-email-comms'
import { Route as ApiPublicSlackStuckMerchantsDigestRouteImport } from './routes/api/public/slack-stuck-merchants-digest'
import { Route as ApiPublicTenantIntegrationsRouteImport } from './routes/api/public/tenant-integrations'
import { Route as ApiPublicUpdateUserRouteImport } from './routes/api/public/update-user'
import { Route as ApiPublicUploadProjectPdfRouteImport } from './routes/api/public/upload-project-pdf'
import { Route as DashReportsPredefinedReportTypeRouteImport } from './routes/_dash.reports.predefined.$reportType'
import { Route as ApiPublicMerchantPortalDataSplatRouteImport } from './routes/api/public/merchant-portal-data.$'
import { Route as ApiPublicV1HealthRouteImport } from './routes/api/public/v1/health'
import { Route as ApiPublicV1ProjectsRouteImport } from './routes/api/public/v1/projects'
import { Route as ApiPublicV1UsersRouteImport } from './routes/api/public/v1/users'
import { Route as ApiPublicV1ProjectsIdRouteImport } from './routes/api/public/v1/projects.$id'

const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const BrdRoute = BrdRouteImport.update({
  id: '/brd',
  path: '/brd',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const DashArchivedRoute = DashArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardRoute = DashDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashRoute,
} as any)
const DashEmailsRoute = DashEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => DashRoute,
} as any)
const DashGoLiveRoute = DashGoLiveRouteImport.update({
  id: '/go-live',
  path: '/go-live',
  getParentRoute: () => DashRoute,
} as any)
const DashPlatformsRoute = DashPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => DashRoute,
} as any)
const DashRisksRoute = DashRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => DashRoute,
} as any)
const DashShopifyLtEmailsRoute = DashShopifyLtEmailsRouteImport.update({
  id: '/shopify-lt-emails',
  path: '/shopify-lt-emails',
  getParentRoute: () => DashRoute,
} as any)
const DashShopifySmeRoute = DashShopifySmeRouteImport.update({
  id: '/shopify-sme',
  path: '/shopify-sme',
  getParentRoute: () => DashRoute,
} as any)
const DashTenantsRoute = DashTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => DashRoute,
} as any)
const PortalMidRoute = PortalMidRouteImport.update({
  id: '/$mid',
  path: '/$mid',
  getParentRoute: () => PortalRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashProjectsGoLiveRoute = DashProjectsGoLiveRouteImport.update({
  id: '/projects/go-live',
  path: '/projects/go-live',
  getParentRoute: () => DashRoute,
} as any)
const DashProjectsKanbanRoute = DashProjectsKanbanRouteImport.update({
  id: '/projects/kanban',
  path: '/projects/kanban',
  getParentRoute: () => DashRoute,
} as any)
const DashProjectsListRoute = DashProjectsListRouteImport.update({
  id: '/projects/list',
  path: '/projects/list',
  getParentRoute: () => DashRoute,
} as any)
const DashReportsSubTabRoute = DashReportsSubTabRouteImport.update({
  id: '/reports/$subTab',
  path: '/reports/$subTab',
  getParentRoute: () => DashRoute,
} as any)
const DashSettingsSubTabRoute = DashSettingsSubTabRouteImport.update({
  id: '/settings/$subTab',
  path: '/settings/$subTab',
  getParentRoute: () => DashRoute,
} as any)
const ApiPublicAiActionsRoute = ApiPublicAiActionsRouteImport.update({
  id: '/api/public/ai-actions',
  path: '/api/public/ai-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiChatRoute = ApiPublicAiChatRouteImport.update({
  id: '/api/public/ai-chat',
  path: '/api/public/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiFieldMappingRoute = ApiPublicAiFieldMappingRouteImport.update({
  id: '/api/public/ai-field-mapping',
  path: '/api/public/ai-field-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiProjectInsightsRoute =
  ApiPublicAiProjectInsightsRouteImport.update({
    id: '/api/public/ai-project-insights',
    path: '/api/public/ai-project-insights',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicApiKeysRoute = ApiPublicApiKeysRouteImport.update({
  id: '/api/public/api-keys',
  path: '/api/public/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAssignShopifySmeOwnerRoute =
  ApiPublicAssignShopifySmeOwnerRouteImport.update({
    id: '/api/public/assign-shopify-sme-owner',
    path: '/api/public/assign-shopify-sme-owner',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBackfillShopifySmeAssignmentsRoute =
  ApiPublicBackfillShopifySmeAssignmentsRouteImport.update({
    id: '/api/public/backfill-shopify-sme-assignments',
    path: '/api/public/backfill-shopify-sme-assignments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBrdFormApiRoute = ApiPublicBrdFormApiRouteImport.update({
  id: '/api/public/brd-form-api',
  path: '/api/public/brd-form-api',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckOverdueTasksRoute =
  ApiPublicCheckOverdueTasksRouteImport.update({
    id: '/api/public/check-overdue-tasks',
    path: '/api/public/check-overdue-tasks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCreateJiraTicketRoute =
  ApiPublicCreateJiraTicketRouteImport.update({
    id: '/api/public/create-jira-ticket',
    path: '/api/public/create-jira-ticket',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCreateUserRoute = ApiPublicCreateUserRouteImport.update({
  id: '/api/public/create-user',
  path: '/api/public/create-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRoute = ApiPublicCronRouteImport.update({
  id: '/api/public/cron',
  path: '/api/public/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeleteUserRoute = ApiPublicDeleteUserRouteImport.update({
  id: '/api/public/delete-user',
  path: '/api/public/delete-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEnrichGoliveTrackerRoute =
  ApiPublicEnrichGoliveTrackerRouteImport.update({
    id: '/api/public/enrich-golive-tracker',
    path: '/api/public/enrich-golive-tracker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFetchProjectEmailsRoute =
  ApiPublicFetchProjectEmailsRouteImport.update({
    id: '/api/public/fetch-project-emails',
    path: '/api/public/fetch-project-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFetchProjectJiraTicketsRoute =
  ApiPublicFetchProjectJiraTicketsRouteImport.update({
    id: '/api/public/fetch-project-jira-tickets',
    path: '/api/public/fetch-project-jira-tickets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGetProjectLinksRoute =
  ApiPublicGetProjectLinksRouteImport.update({
    id: '/api/public/get-project-links',
    path: '/api/public/get-project-links',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJiraCreateUrlRoute = ApiPublicJiraCreateUrlRouteImport.update({
  id: '/api/public/jira-create-url',
  path: '/api/public/jira-create-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKwikassistAiChatRoute =
  ApiPublicKwikassistAiChatRouteImport.update({
    id: '/api/public/kwikassist-ai-chat',
    path: '/api/public/kwikassist-ai-chat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMerchantPortalDataRoute =
  ApiPublicMerchantPortalDataRouteImport.update({
    id: '/api/public/merchant-portal-data',
    path: '/api/public/merchant-portal-data',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPollEmailsRoute = ApiPublicPollEmailsRouteImport.update({
  id: '/api/public/poll-emails',
  path: '/api/public/poll-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPollPlatformGoliveEmailsRoute =
  ApiPublicPollPlatformGoliveEmailsRouteImport.update({
    id: '/api/public/poll-platform-golive-emails',
    path: '/api/public/poll-platform-golive-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPollShopifySmeEmailsRoute =
  ApiPublicPollShopifySmeEmailsRouteImport.update({
    id: '/api/public/poll-shopify-sme-emails',
    path: '/api/public/poll-shopify-sme-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSandboxTestRoute = ApiPublicSandboxTestRouteImport.update({
  id: '/api/public/sandbox-test',
  path: '/api/public/sandbox-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendMovementReportRoute =
  ApiPublicSendMovementReportRouteImport.update({
    id: '/api/public/send-movement-report',
    path: '/api/public/send-movement-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSendNotificationRoute =
  ApiPublicSendNotificationRouteImport.update({
    id: '/api/public/send-notification',
    path: '/api/public/send-notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSendPlatformWelcomeRoute =
  ApiPublicSendPlatformWelcomeRouteImport.update({
    id: '/api/public/send-platform-welcome',
    path: '/api/public/send-platform-welcome',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSendScheduledMovementReportRoute =
  ApiPublicSendScheduledMovementReportRouteImport.update({
    id: '/api/public/send-scheduled-movement-report',
    path: '/api/public/send-scheduled-movement-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSendScheduledReportRoute =
  ApiPublicSendScheduledReportRouteImport.update({
    id: '/api/public/send-scheduled-report',
    path: '/api/public/send-scheduled-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSendScheduledTatReportRoute =
  ApiPublicSendScheduledTatReportRouteImport.update({
    id: '/api/public/send-scheduled-tat-report',
    path: '/api/public/send-scheduled-tat-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSetPasswordRoute = ApiPublicSetPasswordRouteImport.update({
  id: '/api/public/set-password',
  path: '/api/public/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyLtEmailCommsRoute =
  ApiPublicShopifyLtEmailCommsRouteImport.update({
    id: '/api/public/shopify-lt-email-comms',
    path: '/api/public/shopify-lt-email-comms',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSlackStuckMerchantsDigestRoute =
  ApiPublicSlackStuckMerchantsDigestRouteImport.update({
    id: '/api/public/slack-stuck-merchants-digest',
    path: '/api/public/slack-stuck-merchants-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTenantIntegrationsRoute =
  ApiPublicTenantIntegrationsRouteImport.update({
    id: '/api/public/tenant-integrations',
    path: '/api/public/tenant-integrations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUpdateUserRoute = ApiPublicUpdateUserRouteImport.update({
  id: '/api/public/update-user',
  path: '/api/public/update-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadProjectPdfRoute =
  ApiPublicUploadProjectPdfRouteImport.update({
    id: '/api/public/upload-project-pdf',
    path: '/api/public/upload-project-pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashReportsPredefinedReportTypeRoute =
  DashReportsPredefinedReportTypeRouteImport.update({
    id: '/reports/predefined/$reportType',
    path: '/reports/predefined/$reportType',
    getParentRoute: () => DashRoute,
  } as any)
const ApiPublicMerchantPortalDataSplatRoute =
  ApiPublicMerchantPortalDataSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => ApiPublicMerchantPortalDataRoute,
  } as any)
const ApiPublicV1HealthRoute = ApiPublicV1HealthRouteImport.update({
  id: '/api/public/v1/health',
  path: '/api/public/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProjectsRoute = ApiPublicV1ProjectsRouteImport.update({
  id: '/api/public/v1/projects',
  path: '/api/public/v1/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1UsersRoute = ApiPublicV1UsersRouteImport.update({
  id: '/api/public/v1/users',
  path: '/api/public/v1/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProjectsIdRoute = ApiPublicV1ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashIndexRoute
  '/brd': typeof BrdRoute
  '/portal': typeof PortalRouteWithChildren
  '/archived': typeof DashArchivedRoute
  '/dashboard': typeof DashDashboardRoute
  '/emails': typeof DashEmailsRoute
  '/go-live': typeof DashGoLiveRoute
  '/platforms': typeof DashPlatformsRoute
  '/risks': typeof DashRisksRoute
  '/shopify-lt-emails': typeof DashShopifyLtEmailsRoute
  '/shopify-sme': typeof DashShopifySmeRoute
  '/tenants': typeof DashTenantsRoute
  '/portal/$mid': typeof PortalMidRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/go-live': typeof DashProjectsGoLiveRoute
  '/projects/kanban': typeof DashProjectsKanbanRoute
  '/projects/list': typeof DashProjectsListRoute
  '/reports/$subTab': typeof DashReportsSubTabRoute
  '/settings/$subTab': typeof DashSettingsSubTabRoute
  '/api/public/ai-actions': typeof ApiPublicAiActionsRoute
  '/api/public/ai-chat': typeof ApiPublicAiChatRoute
  '/api/public/ai-field-mapping': typeof ApiPublicAiFieldMappingRoute
  '/api/public/ai-project-insights': typeof ApiPublicAiProjectInsightsRoute
  '/api/public/api-keys': typeof ApiPublicApiKeysRoute
  '/api/public/assign-shopify-sme-owner': typeof ApiPublicAssignShopifySmeOwnerRoute
  '/api/public/backfill-shopify-sme-assignments': typeof ApiPublicBackfillShopifySmeAssignmentsRoute
  '/api/public/brd-form-api': typeof ApiPublicBrdFormApiRoute
  '/api/public/check-overdue-tasks': typeof ApiPublicCheckOverdueTasksRoute
  '/api/public/create-jira-ticket': typeof ApiPublicCreateJiraTicketRoute
  '/api/public/create-user': typeof ApiPublicCreateUserRoute
  '/api/public/cron': typeof ApiPublicCronRoute
  '/api/public/delete-user': typeof ApiPublicDeleteUserRoute
  '/api/public/enrich-golive-tracker': typeof ApiPublicEnrichGoliveTrackerRoute
  '/api/public/fetch-project-emails': typeof ApiPublicFetchProjectEmailsRoute
  '/api/public/fetch-project-jira-tickets': typeof ApiPublicFetchProjectJiraTicketsRoute
  '/api/public/get-project-links': typeof ApiPublicGetProjectLinksRoute
  '/api/public/jira-create-url': typeof ApiPublicJiraCreateUrlRoute
  '/api/public/kwikassist-ai-chat': typeof ApiPublicKwikassistAiChatRoute
  '/api/public/merchant-portal-data': typeof ApiPublicMerchantPortalDataRouteWithChildren
  '/api/public/poll-emails': typeof ApiPublicPollEmailsRoute
  '/api/public/poll-platform-golive-emails': typeof ApiPublicPollPlatformGoliveEmailsRoute
  '/api/public/poll-shopify-sme-emails': typeof ApiPublicPollShopifySmeEmailsRoute
  '/api/public/sandbox-test': typeof ApiPublicSandboxTestRoute
  '/api/public/send-movement-report': typeof ApiPublicSendMovementReportRoute
  '/api/public/send-notification': typeof ApiPublicSendNotificationRoute
  '/api/public/send-platform-welcome': typeof ApiPublicSendPlatformWelcomeRoute
  '/api/public/send-scheduled-movement-report': typeof ApiPublicSendScheduledMovementReportRoute
  '/api/public/send-scheduled-report': typeof ApiPublicSendScheduledReportRoute
  '/api/public/send-scheduled-tat-report': typeof ApiPublicSendScheduledTatReportRoute
  '/api/public/set-password': typeof ApiPublicSetPasswordRoute
  '/api/public/shopify-lt-email-comms': typeof ApiPublicShopifyLtEmailCommsRoute
  '/api/public/slack-stuck-merchants-digest': typeof ApiPublicSlackStuckMerchantsDigestRoute
  '/api/public/tenant-integrations': typeof ApiPublicTenantIntegrationsRoute
  '/api/public/update-user': typeof ApiPublicUpdateUserRoute
  '/api/public/upload-project-pdf': typeof ApiPublicUploadProjectPdfRoute
  '/reports/predefined/$reportType': typeof DashReportsPredefinedReportTypeRoute
  '/api/public/merchant-portal-data/$': typeof ApiPublicMerchantPortalDataSplatRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/projects': typeof ApiPublicV1ProjectsRouteWithChildren
  '/api/public/v1/users': typeof ApiPublicV1UsersRoute
  '/api/public/v1/projects/$id': typeof ApiPublicV1ProjectsIdRoute
}
export interface FileRoutesByTo {
  '/brd': typeof BrdRoute
  '/portal': typeof PortalRouteWithChildren
  '/archived': typeof DashArchivedRoute
  '/dashboard': typeof DashDashboardRoute
  '/emails': typeof DashEmailsRoute
  '/go-live': typeof DashGoLiveRoute
  '/platforms': typeof DashPlatformsRoute
  '/risks': typeof DashRisksRoute
  '/shopify-lt-emails': typeof DashShopifyLtEmailsRoute
  '/shopify-sme': typeof DashShopifySmeRoute
  '/tenants': typeof DashTenantsRoute
  '/portal/$mid': typeof PortalMidRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/': typeof DashIndexRoute
  '/projects/go-live': typeof DashProjectsGoLiveRoute
  '/projects/kanban': typeof DashProjectsKanbanRoute
  '/projects/list': typeof DashProjectsListRoute
  '/reports/$subTab': typeof DashReportsSubTabRoute
  '/settings/$subTab': typeof DashSettingsSubTabRoute
  '/api/public/ai-actions': typeof ApiPublicAiActionsRoute
  '/api/public/ai-chat': typeof ApiPublicAiChatRoute
  '/api/public/ai-field-mapping': typeof ApiPublicAiFieldMappingRoute
  '/api/public/ai-project-insights': typeof ApiPublicAiProjectInsightsRoute
  '/api/public/api-keys': typeof ApiPublicApiKeysRoute
  '/api/public/assign-shopify-sme-owner': typeof ApiPublicAssignShopifySmeOwnerRoute
  '/api/public/backfill-shopify-sme-assignments': typeof ApiPublicBackfillShopifySmeAssignmentsRoute
  '/api/public/brd-form-api': typeof ApiPublicBrdFormApiRoute
  '/api/public/check-overdue-tasks': typeof ApiPublicCheckOverdueTasksRoute
  '/api/public/create-jira-ticket': typeof ApiPublicCreateJiraTicketRoute
  '/api/public/create-user': typeof ApiPublicCreateUserRoute
  '/api/public/cron': typeof ApiPublicCronRoute
  '/api/public/delete-user': typeof ApiPublicDeleteUserRoute
  '/api/public/enrich-golive-tracker': typeof ApiPublicEnrichGoliveTrackerRoute
  '/api/public/fetch-project-emails': typeof ApiPublicFetchProjectEmailsRoute
  '/api/public/fetch-project-jira-tickets': typeof ApiPublicFetchProjectJiraTicketsRoute
  '/api/public/get-project-links': typeof ApiPublicGetProjectLinksRoute
  '/api/public/jira-create-url': typeof ApiPublicJiraCreateUrlRoute
  '/api/public/kwikassist-ai-chat': typeof ApiPublicKwikassistAiChatRoute
  '/api/public/merchant-portal-data': typeof ApiPublicMerchantPortalDataRouteWithChildren
  '/api/public/poll-emails': typeof ApiPublicPollEmailsRoute
  '/api/public/poll-platform-golive-emails': typeof ApiPublicPollPlatformGoliveEmailsRoute
  '/api/public/poll-shopify-sme-emails': typeof ApiPublicPollShopifySmeEmailsRoute
  '/api/public/sandbox-test': typeof ApiPublicSandboxTestRoute
  '/api/public/send-movement-report': typeof ApiPublicSendMovementReportRoute
  '/api/public/send-notification': typeof ApiPublicSendNotificationRoute
  '/api/public/send-platform-welcome': typeof ApiPublicSendPlatformWelcomeRoute
  '/api/public/send-scheduled-movement-report': typeof ApiPublicSendScheduledMovementReportRoute
  '/api/public/send-scheduled-report': typeof ApiPublicSendScheduledReportRoute
  '/api/public/send-scheduled-tat-report': typeof ApiPublicSendScheduledTatReportRoute
  '/api/public/set-password': typeof ApiPublicSetPasswordRoute
  '/api/public/shopify-lt-email-comms': typeof ApiPublicShopifyLtEmailCommsRoute
  '/api/public/slack-stuck-merchants-digest': typeof ApiPublicSlackStuckMerchantsDigestRoute
  '/api/public/tenant-integrations': typeof ApiPublicTenantIntegrationsRoute
  '/api/public/update-user': typeof ApiPublicUpdateUserRoute
  '/api/public/upload-project-pdf': typeof ApiPublicUploadProjectPdfRoute
  '/reports/predefined/$reportType': typeof DashReportsPredefinedReportTypeRoute
  '/api/public/merchant-portal-data/$': typeof ApiPublicMerchantPortalDataSplatRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/projects': typeof ApiPublicV1ProjectsRouteWithChildren
  '/api/public/v1/users': typeof ApiPublicV1UsersRoute
  '/api/public/v1/projects/$id': typeof ApiPublicV1ProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dash': typeof DashRouteWithChildren
  '/brd': typeof BrdRoute
  '/portal': typeof PortalRouteWithChildren
  '/_dash/archived': typeof DashArchivedRoute
  '/_dash/dashboard': typeof DashDashboardRoute
  '/_dash/emails': typeof DashEmailsRoute
  '/_dash/go-live': typeof DashGoLiveRoute
  '/_dash/platforms': typeof DashPlatformsRoute
  '/_dash/risks': typeof DashRisksRoute
  '/_dash/shopify-lt-emails': typeof DashShopifyLtEmailsRoute
  '/_dash/shopify-sme': typeof DashShopifySmeRoute
  '/_dash/tenants': typeof DashTenantsRoute
  '/portal/$mid': typeof PortalMidRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/_dash/': typeof DashIndexRoute
  '/_dash/projects/go-live': typeof DashProjectsGoLiveRoute
  '/_dash/projects/kanban': typeof DashProjectsKanbanRoute
  '/_dash/projects/list': typeof DashProjectsListRoute
  '/_dash/reports/$subTab': typeof DashReportsSubTabRoute
  '/_dash/settings/$subTab': typeof DashSettingsSubTabRoute
  '/api/public/ai-actions': typeof ApiPublicAiActionsRoute
  '/api/public/ai-chat': typeof ApiPublicAiChatRoute
  '/api/public/ai-field-mapping': typeof ApiPublicAiFieldMappingRoute
  '/api/public/ai-project-insights': typeof ApiPublicAiProjectInsightsRoute
  '/api/public/api-keys': typeof ApiPublicApiKeysRoute
  '/api/public/assign-shopify-sme-owner': typeof ApiPublicAssignShopifySmeOwnerRoute
  '/api/public/backfill-shopify-sme-assignments': typeof ApiPublicBackfillShopifySmeAssignmentsRoute
  '/api/public/brd-form-api': typeof ApiPublicBrdFormApiRoute
  '/api/public/check-overdue-tasks': typeof ApiPublicCheckOverdueTasksRoute
  '/api/public/create-jira-ticket': typeof ApiPublicCreateJiraTicketRoute
  '/api/public/create-user': typeof ApiPublicCreateUserRoute
  '/api/public/cron': typeof ApiPublicCronRoute
  '/api/public/delete-user': typeof ApiPublicDeleteUserRoute
  '/api/public/enrich-golive-tracker': typeof ApiPublicEnrichGoliveTrackerRoute
  '/api/public/fetch-project-emails': typeof ApiPublicFetchProjectEmailsRoute
  '/api/public/fetch-project-jira-tickets': typeof ApiPublicFetchProjectJiraTicketsRoute
  '/api/public/get-project-links': typeof ApiPublicGetProjectLinksRoute
  '/api/public/jira-create-url': typeof ApiPublicJiraCreateUrlRoute
  '/api/public/kwikassist-ai-chat': typeof ApiPublicKwikassistAiChatRoute
  '/api/public/merchant-portal-data': typeof ApiPublicMerchantPortalDataRouteWithChildren
  '/api/public/poll-emails': typeof ApiPublicPollEmailsRoute
  '/api/public/poll-platform-golive-emails': typeof ApiPublicPollPlatformGoliveEmailsRoute
  '/api/public/poll-shopify-sme-emails': typeof ApiPublicPollShopifySmeEmailsRoute
  '/api/public/sandbox-test': typeof ApiPublicSandboxTestRoute
  '/api/public/send-movement-report': typeof ApiPublicSendMovementReportRoute
  '/api/public/send-notification': typeof ApiPublicSendNotificationRoute
  '/api/public/send-platform-welcome': typeof ApiPublicSendPlatformWelcomeRoute
  '/api/public/send-scheduled-movement-report': typeof ApiPublicSendScheduledMovementReportRoute
  '/api/public/send-scheduled-report': typeof ApiPublicSendScheduledReportRoute
  '/api/public/send-scheduled-tat-report': typeof ApiPublicSendScheduledTatReportRoute
  '/api/public/set-password': typeof ApiPublicSetPasswordRoute
  '/api/public/shopify-lt-email-comms': typeof ApiPublicShopifyLtEmailCommsRoute
  '/api/public/slack-stuck-merchants-digest': typeof ApiPublicSlackStuckMerchantsDigestRoute
  '/api/public/tenant-integrations': typeof ApiPublicTenantIntegrationsRoute
  '/api/public/update-user': typeof ApiPublicUpdateUserRoute
  '/api/public/upload-project-pdf': typeof ApiPublicUploadProjectPdfRoute
  '/_dash/reports/predefined/$reportType': typeof DashReportsPredefinedReportTypeRoute
  '/api/public/merchant-portal-data/$': typeof ApiPublicMerchantPortalDataSplatRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/projects': typeof ApiPublicV1ProjectsRouteWithChildren
  '/api/public/v1/users': typeof ApiPublicV1UsersRoute
  '/api/public/v1/projects/$id': typeof ApiPublicV1ProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brd'
    | '/portal'
    | '/archived'
    | '/dashboard'
    | '/emails'
    | '/go-live'
    | '/platforms'
    | '/risks'
    | '/shopify-lt-emails'
    | '/shopify-sme'
    | '/tenants'
    | '/portal/$mid'
    | '/projects/$projectId'
    | '/projects/go-live'
    | '/projects/kanban'
    | '/projects/list'
    | '/reports/$subTab'
    | '/settings/$subTab'
    | '/api/public/ai-actions'
    | '/api/public/ai-chat'
    | '/api/public/ai-field-mapping'
    | '/api/public/ai-project-insights'
    | '/api/public/api-keys'
    | '/api/public/assign-shopify-sme-owner'
    | '/api/public/backfill-shopify-sme-assignments'
    | '/api/public/brd-form-api'
    | '/api/public/check-overdue-tasks'
    | '/api/public/create-jira-ticket'
    | '/api/public/create-user'
    | '/api/public/cron'
    | '/api/public/delete-user'
    | '/api/public/enrich-golive-tracker'
    | '/api/public/fetch-project-emails'
    | '/api/public/fetch-project-jira-tickets'
    | '/api/public/get-project-links'
    | '/api/public/jira-create-url'
    | '/api/public/kwikassist-ai-chat'
    | '/api/public/merchant-portal-data'
    | '/api/public/poll-emails'
    | '/api/public/poll-platform-golive-emails'
    | '/api/public/poll-shopify-sme-emails'
    | '/api/public/sandbox-test'
    | '/api/public/send-movement-report'
    | '/api/public/send-notification'
    | '/api/public/send-platform-welcome'
    | '/api/public/send-scheduled-movement-report'
    | '/api/public/send-scheduled-report'
    | '/api/public/send-scheduled-tat-report'
    | '/api/public/set-password'
    | '/api/public/shopify-lt-email-comms'
    | '/api/public/slack-stuck-merchants-digest'
    | '/api/public/tenant-integrations'
    | '/api/public/update-user'
    | '/api/public/upload-project-pdf'
    | '/reports/predefined/$reportType'
    | '/api/public/merchant-portal-data/$'
    | '/api/public/v1/health'
    | '/api/public/v1/projects'
    | '/api/public/v1/users'
    | '/api/public/v1/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/brd'
    | '/portal'
    | '/archived'
    | '/dashboard'
    | '/emails'
    | '/go-live'
    | '/platforms'
    | '/risks'
    | '/shopify-lt-emails'
    | '/shopify-sme'
    | '/tenants'
    | '/portal/$mid'
    | '/projects/$projectId'
    | '/'
    | '/projects/go-live'
    | '/projects/kanban'
    | '/projects/list'
    | '/reports/$subTab'
    | '/settings/$subTab'
    | '/api/public/ai-actions'
    | '/api/public/ai-chat'
    | '/api/public/ai-field-mapping'
    | '/api/public/ai-project-insights'
    | '/api/public/api-keys'
    | '/api/public/assign-shopify-sme-owner'
    | '/api/public/backfill-shopify-sme-assignments'
    | '/api/public/brd-form-api'
    | '/api/public/check-overdue-tasks'
    | '/api/public/create-jira-ticket'
    | '/api/public/create-user'
    | '/api/public/cron'
    | '/api/public/delete-user'
    | '/api/public/enrich-golive-tracker'
    | '/api/public/fetch-project-emails'
    | '/api/public/fetch-project-jira-tickets'
    | '/api/public/get-project-links'
    | '/api/public/jira-create-url'
    | '/api/public/kwikassist-ai-chat'
    | '/api/public/merchant-portal-data'
    | '/api/public/poll-emails'
    | '/api/public/poll-platform-golive-emails'
    | '/api/public/poll-shopify-sme-emails'
    | '/api/public/sandbox-test'
    | '/api/public/send-movement-report'
    | '/api/public/send-notification'
    | '/api/public/send-platform-welcome'
    | '/api/public/send-scheduled-movement-report'
    | '/api/public/send-scheduled-report'
    | '/api/public/send-scheduled-tat-report'
    | '/api/public/set-password'
    | '/api/public/shopify-lt-email-comms'
    | '/api/public/slack-stuck-merchants-digest'
    | '/api/public/tenant-integrations'
    | '/api/public/update-user'
    | '/api/public/upload-project-pdf'
    | '/reports/predefined/$reportType'
    | '/api/public/merchant-portal-data/$'
    | '/api/public/v1/health'
    | '/api/public/v1/projects'
    | '/api/public/v1/users'
    | '/api/public/v1/projects/$id'
  id:
    | '__root__'
    | '/_dash'
    | '/brd'
    | '/portal'
    | '/_dash/archived'
    | '/_dash/dashboard'
    | '/_dash/emails'
    | '/_dash/go-live'
    | '/_dash/platforms'
    | '/_dash/risks'
    | '/_dash/shopify-lt-emails'
    | '/_dash/shopify-sme'
    | '/_dash/tenants'
    | '/portal/$mid'
    | '/projects/$projectId'
    | '/_dash/'
    | '/_dash/projects/go-live'
    | '/_dash/projects/kanban'
    | '/_dash/projects/list'
    | '/_dash/reports/$subTab'
    | '/_dash/settings/$subTab'
    | '/api/public/ai-actions'
    | '/api/public/ai-chat'
    | '/api/public/ai-field-mapping'
    | '/api/public/ai-project-insights'
    | '/api/public/api-keys'
    | '/api/public/assign-shopify-sme-owner'
    | '/api/public/backfill-shopify-sme-assignments'
    | '/api/public/brd-form-api'
    | '/api/public/check-overdue-tasks'
    | '/api/public/create-jira-ticket'
    | '/api/public/create-user'
    | '/api/public/cron'
    | '/api/public/delete-user'
    | '/api/public/enrich-golive-tracker'
    | '/api/public/fetch-project-emails'
    | '/api/public/fetch-project-jira-tickets'
    | '/api/public/get-project-links'
    | '/api/public/jira-create-url'
    | '/api/public/kwikassist-ai-chat'
    | '/api/public/merchant-portal-data'
    | '/api/public/poll-emails'
    | '/api/public/poll-platform-golive-emails'
    | '/api/public/poll-shopify-sme-emails'
    | '/api/public/sandbox-test'
    | '/api/public/send-movement-report'
    | '/api/public/send-notification'
    | '/api/public/send-platform-welcome'
    | '/api/public/send-scheduled-movement-report'
    | '/api/public/send-scheduled-report'
    | '/api/public/send-scheduled-tat-report'
    | '/api/public/set-password'
    | '/api/public/shopify-lt-email-comms'
    | '/api/public/slack-stuck-merchants-digest'
    | '/api/public/tenant-integrations'
    | '/api/public/update-user'
    | '/api/public/upload-project-pdf'
    | '/_dash/reports/predefined/$reportType'
    | '/api/public/merchant-portal-data/$'
    | '/api/public/v1/health'
    | '/api/public/v1/projects'
    | '/api/public/v1/users'
    | '/api/public/v1/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashRoute: typeof DashRouteWithChildren
  BrdRoute: typeof BrdRoute
  PortalRoute: typeof PortalRouteWithChildren
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ApiPublicAiActionsRoute: typeof ApiPublicAiActionsRoute
  ApiPublicAiChatRoute: typeof ApiPublicAiChatRoute
  ApiPublicAiFieldMappingRoute: typeof ApiPublicAiFieldMappingRoute
  ApiPublicAiProjectInsightsRoute: typeof ApiPublicAiProjectInsightsRoute
  ApiPublicApiKeysRoute: typeof ApiPublicApiKeysRoute
  ApiPublicAssignShopifySmeOwnerRoute: typeof ApiPublicAssignShopifySmeOwnerRoute
  ApiPublicBackfillShopifySmeAssignmentsRoute: typeof ApiPublicBackfillShopifySmeAssignmentsRoute
  ApiPublicBrdFormApiRoute: typeof ApiPublicBrdFormApiRoute
  ApiPublicCheckOverdueTasksRoute: typeof ApiPublicCheckOverdueTasksRoute
  ApiPublicCreateJiraTicketRoute: typeof ApiPublicCreateJiraTicketRoute
  ApiPublicCreateUserRoute: typeof ApiPublicCreateUserRoute
  ApiPublicCronRoute: typeof ApiPublicCronRoute
  ApiPublicDeleteUserRoute: typeof ApiPublicDeleteUserRoute
  ApiPublicEnrichGoliveTrackerRoute: typeof ApiPublicEnrichGoliveTrackerRoute
  ApiPublicFetchProjectEmailsRoute: typeof ApiPublicFetchProjectEmailsRoute
  ApiPublicFetchProjectJiraTicketsRoute: typeof ApiPublicFetchProjectJiraTicketsRoute
  ApiPublicGetProjectLinksRoute: typeof ApiPublicGetProjectLinksRoute
  ApiPublicJiraCreateUrlRoute: typeof ApiPublicJiraCreateUrlRoute
  ApiPublicKwikassistAiChatRoute: typeof ApiPublicKwikassistAiChatRoute
  ApiPublicMerchantPortalDataRoute: typeof ApiPublicMerchantPortalDataRouteWithChildren
  ApiPublicPollEmailsRoute: typeof ApiPublicPollEmailsRoute
  ApiPublicPollPlatformGoliveEmailsRoute: typeof ApiPublicPollPlatformGoliveEmailsRoute
  ApiPublicPollShopifySmeEmailsRoute: typeof ApiPublicPollShopifySmeEmailsRoute
  ApiPublicSandboxTestRoute: typeof ApiPublicSandboxTestRoute
  ApiPublicSendMovementReportRoute: typeof ApiPublicSendMovementReportRoute
  ApiPublicSendNotificationRoute: typeof ApiPublicSendNotificationRoute
  ApiPublicSendPlatformWelcomeRoute: typeof ApiPublicSendPlatformWelcomeRoute
  ApiPublicSendScheduledMovementReportRoute: typeof ApiPublicSendScheduledMovementReportRoute
  ApiPublicSendScheduledReportRoute: typeof ApiPublicSendScheduledReportRoute
  ApiPublicSendScheduledTatReportRoute: typeof ApiPublicSendScheduledTatReportRoute
  ApiPublicSetPasswordRoute: typeof ApiPublicSetPasswordRoute
  ApiPublicShopifyLtEmailCommsRoute: typeof ApiPublicShopifyLtEmailCommsRoute
  ApiPublicSlackStuckMerchantsDigestRoute: typeof ApiPublicSlackStuckMerchantsDigestRoute
  ApiPublicTenantIntegrationsRoute: typeof ApiPublicTenantIntegrationsRoute
  ApiPublicUpdateUserRoute: typeof ApiPublicUpdateUserRoute
  ApiPublicUploadProjectPdfRoute: typeof ApiPublicUploadProjectPdfRoute
  ApiPublicV1HealthRoute: typeof ApiPublicV1HealthRoute
  ApiPublicV1ProjectsRoute: typeof ApiPublicV1ProjectsRouteWithChildren
  ApiPublicV1UsersRoute: typeof ApiPublicV1UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brd': {
      id: '/brd'
      path: '/brd'
      fullPath: '/brd'
      preLoaderRoute: typeof BrdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/': {
      id: '/_dash/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/archived': {
      id: '/_dash/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof DashArchivedRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard': {
      id: '/_dash/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashDashboardRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/emails': {
      id: '/_dash/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof DashEmailsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/go-live': {
      id: '/_dash/go-live'
      path: '/go-live'
      fullPath: '/go-live'
      preLoaderRoute: typeof DashGoLiveRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/platforms': {
      id: '/_dash/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof DashPlatformsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/risks': {
      id: '/_dash/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof DashRisksRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/shopify-lt-emails': {
      id: '/_dash/shopify-lt-emails'
      path: '/shopify-lt-emails'
      fullPath: '/shopify-lt-emails'
      preLoaderRoute: typeof DashShopifyLtEmailsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/shopify-sme': {
      id: '/_dash/shopify-sme'
      path: '/shopify-sme'
      fullPath: '/shopify-sme'
      preLoaderRoute: typeof DashShopifySmeRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/tenants': {
      id: '/_dash/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof DashTenantsRouteImport
      parentRoute: typeof DashRoute
    }
    '/portal/$mid': {
      id: '/portal/$mid'
      path: '/$mid'
      fullPath: '/portal/$mid'
      preLoaderRoute: typeof PortalMidRouteImport
      parentRoute: typeof PortalRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/projects/go-live': {
      id: '/_dash/projects/go-live'
      path: '/projects/go-live'
      fullPath: '/projects/go-live'
      preLoaderRoute: typeof DashProjectsGoLiveRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/projects/kanban': {
      id: '/_dash/projects/kanban'
      path: '/projects/kanban'
      fullPath: '/projects/kanban'
      preLoaderRoute: typeof DashProjectsKanbanRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/projects/list': {
      id: '/_dash/projects/list'
      path: '/projects/list'
      fullPath: '/projects/list'
      preLoaderRoute: typeof DashProjectsListRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/reports/$subTab': {
      id: '/_dash/reports/$subTab'
      path: '/reports/$subTab'
      fullPath: '/reports/$subTab'
      preLoaderRoute: typeof DashReportsSubTabRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/settings/$subTab': {
      id: '/_dash/settings/$subTab'
      path: '/settings/$subTab'
      fullPath: '/settings/$subTab'
      preLoaderRoute: typeof DashSettingsSubTabRouteImport
      parentRoute: typeof DashRoute
    }
    '/api/public/ai-actions': {
      id: '/api/public/ai-actions'
      path: '/api/public/ai-actions'
      fullPath: '/api/public/ai-actions'
      preLoaderRoute: typeof ApiPublicAiActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-chat': {
      id: '/api/public/ai-chat'
      path: '/api/public/ai-chat'
      fullPath: '/api/public/ai-chat'
      preLoaderRoute: typeof ApiPublicAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-field-mapping': {
      id: '/api/public/ai-field-mapping'
      path: '/api/public/ai-field-mapping'
      fullPath: '/api/public/ai-field-mapping'
      preLoaderRoute: typeof ApiPublicAiFieldMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-project-insights': {
      id: '/api/public/ai-project-insights'
      path: '/api/public/ai-project-insights'
      fullPath: '/api/public/ai-project-insights'
      preLoaderRoute: typeof ApiPublicAiProjectInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/api-keys': {
      id: '/api/public/api-keys'
      path: '/api/public/api-keys'
      fullPath: '/api/public/api-keys'
      preLoaderRoute: typeof ApiPublicApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/assign-shopify-sme-owner': {
      id: '/api/public/assign-shopify-sme-owner'
      path: '/api/public/assign-shopify-sme-owner'
      fullPath: '/api/public/assign-shopify-sme-owner'
      preLoaderRoute: typeof ApiPublicAssignShopifySmeOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backfill-shopify-sme-assignments': {
      id: '/api/public/backfill-shopify-sme-assignments'
      path: '/api/public/backfill-shopify-sme-assignments'
      fullPath: '/api/public/backfill-shopify-sme-assignments'
      preLoaderRoute: typeof ApiPublicBackfillShopifySmeAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brd-form-api': {
      id: '/api/public/brd-form-api'
      path: '/api/public/brd-form-api'
      fullPath: '/api/public/brd-form-api'
      preLoaderRoute: typeof ApiPublicBrdFormApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/check-overdue-tasks': {
      id: '/api/public/check-overdue-tasks'
      path: '/api/public/check-overdue-tasks'
      fullPath: '/api/public/check-overdue-tasks'
      preLoaderRoute: typeof ApiPublicCheckOverdueTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-jira-ticket': {
      id: '/api/public/create-jira-ticket'
      path: '/api/public/create-jira-ticket'
      fullPath: '/api/public/create-jira-ticket'
      preLoaderRoute: typeof ApiPublicCreateJiraTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-user': {
      id: '/api/public/create-user'
      path: '/api/public/create-user'
      fullPath: '/api/public/create-user'
      preLoaderRoute: typeof ApiPublicCreateUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron': {
      id: '/api/public/cron'
      path: '/api/public/cron'
      fullPath: '/api/public/cron'
      preLoaderRoute: typeof ApiPublicCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/delete-user': {
      id: '/api/public/delete-user'
      path: '/api/public/delete-user'
      fullPath: '/api/public/delete-user'
      preLoaderRoute: typeof ApiPublicDeleteUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/enrich-golive-tracker': {
      id: '/api/public/enrich-golive-tracker'
      path: '/api/public/enrich-golive-tracker'
      fullPath: '/api/public/enrich-golive-tracker'
      preLoaderRoute: typeof ApiPublicEnrichGoliveTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fetch-project-emails': {
      id: '/api/public/fetch-project-emails'
      path: '/api/public/fetch-project-emails'
      fullPath: '/api/public/fetch-project-emails'
      preLoaderRoute: typeof ApiPublicFetchProjectEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fetch-project-jira-tickets': {
      id: '/api/public/fetch-project-jira-tickets'
      path: '/api/public/fetch-project-jira-tickets'
      fullPath: '/api/public/fetch-project-jira-tickets'
      preLoaderRoute: typeof ApiPublicFetchProjectJiraTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get-project-links': {
      id: '/api/public/get-project-links'
      path: '/api/public/get-project-links'
      fullPath: '/api/public/get-project-links'
      preLoaderRoute: typeof ApiPublicGetProjectLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jira-create-url': {
      id: '/api/public/jira-create-url'
      path: '/api/public/jira-create-url'
      fullPath: '/api/public/jira-create-url'
      preLoaderRoute: typeof ApiPublicJiraCreateUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kwikassist-ai-chat': {
      id: '/api/public/kwikassist-ai-chat'
      path: '/api/public/kwikassist-ai-chat'
      fullPath: '/api/public/kwikassist-ai-chat'
      preLoaderRoute: typeof ApiPublicKwikassistAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/merchant-portal-data': {
      id: '/api/public/merchant-portal-data'
      path: '/api/public/merchant-portal-data'
      fullPath: '/api/public/merchant-portal-data'
      preLoaderRoute: typeof ApiPublicMerchantPortalDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/poll-emails': {
      id: '/api/public/poll-emails'
      path: '/api/public/poll-emails'
      fullPath: '/api/public/poll-emails'
      preLoaderRoute: typeof ApiPublicPollEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/poll-platform-golive-emails': {
      id: '/api/public/poll-platform-golive-emails'
      path: '/api/public/poll-platform-golive-emails'
      fullPath: '/api/public/poll-platform-golive-emails'
      preLoaderRoute: typeof ApiPublicPollPlatformGoliveEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/poll-shopify-sme-emails': {
      id: '/api/public/poll-shopify-sme-emails'
      path: '/api/public/poll-shopify-sme-emails'
      fullPath: '/api/public/poll-shopify-sme-emails'
      preLoaderRoute: typeof ApiPublicPollShopifySmeEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sandbox-test': {
      id: '/api/public/sandbox-test'
      path: '/api/public/sandbox-test'
      fullPath: '/api/public/sandbox-test'
      preLoaderRoute: typeof ApiPublicSandboxTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-movement-report': {
      id: '/api/public/send-movement-report'
      path: '/api/public/send-movement-report'
      fullPath: '/api/public/send-movement-report'
      preLoaderRoute: typeof ApiPublicSendMovementReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-notification': {
      id: '/api/public/send-notification'
      path: '/api/public/send-notification'
      fullPath: '/api/public/send-notification'
      preLoaderRoute: typeof ApiPublicSendNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-platform-welcome': {
      id: '/api/public/send-platform-welcome'
      path: '/api/public/send-platform-welcome'
      fullPath: '/api/public/send-platform-welcome'
      preLoaderRoute: typeof ApiPublicSendPlatformWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-scheduled-movement-report': {
      id: '/api/public/send-scheduled-movement-report'
      path: '/api/public/send-scheduled-movement-report'
      fullPath: '/api/public/send-scheduled-movement-report'
      preLoaderRoute: typeof ApiPublicSendScheduledMovementReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-scheduled-report': {
      id: '/api/public/send-scheduled-report'
      path: '/api/public/send-scheduled-report'
      fullPath: '/api/public/send-scheduled-report'
      preLoaderRoute: typeof ApiPublicSendScheduledReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-scheduled-tat-report': {
      id: '/api/public/send-scheduled-tat-report'
      path: '/api/public/send-scheduled-tat-report'
      fullPath: '/api/public/send-scheduled-tat-report'
      preLoaderRoute: typeof ApiPublicSendScheduledTatReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/set-password': {
      id: '/api/public/set-password'
      path: '/api/public/set-password'
      fullPath: '/api/public/set-password'
      preLoaderRoute: typeof ApiPublicSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify-lt-email-comms': {
      id: '/api/public/shopify-lt-email-comms'
      path: '/api/public/shopify-lt-email-comms'
      fullPath: '/api/public/shopify-lt-email-comms'
      preLoaderRoute: typeof ApiPublicShopifyLtEmailCommsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/slack-stuck-merchants-digest': {
      id: '/api/public/slack-stuck-merchants-digest'
      path: '/api/public/slack-stuck-merchants-digest'
      fullPath: '/api/public/slack-stuck-merchants-digest'
      preLoaderRoute: typeof ApiPublicSlackStuckMerchantsDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tenant-integrations': {
      id: '/api/public/tenant-integrations'
      path: '/api/public/tenant-integrations'
      fullPath: '/api/public/tenant-integrations'
      preLoaderRoute: typeof ApiPublicTenantIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/update-user': {
      id: '/api/public/update-user'
      path: '/api/public/update-user'
      fullPath: '/api/public/update-user'
      preLoaderRoute: typeof ApiPublicUpdateUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload-project-pdf': {
      id: '/api/public/upload-project-pdf'
      path: '/api/public/upload-project-pdf'
      fullPath: '/api/public/upload-project-pdf'
      preLoaderRoute: typeof ApiPublicUploadProjectPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/reports/predefined/$reportType': {
      id: '/_dash/reports/predefined/$reportType'
      path: '/reports/predefined/$reportType'
      fullPath: '/reports/predefined/$reportType'
      preLoaderRoute: typeof DashReportsPredefinedReportTypeRouteImport
      parentRoute: typeof DashRoute
    }
    '/api/public/merchant-portal-data/$': {
      id: '/api/public/merchant-portal-data/$'
      path: '/$'
      fullPath: '/api/public/merchant-portal-data/$'
      preLoaderRoute: typeof ApiPublicMerchantPortalDataSplatRouteImport
      parentRoute: typeof ApiPublicMerchantPortalDataRoute
    }
    '/api/public/v1/health': {
      id: '/api/public/v1/health'
      path: '/api/public/v1/health'
      fullPath: '/api/public/v1/health'
      preLoaderRoute: typeof ApiPublicV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/projects': {
      id: '/api/public/v1/projects'
      path: '/api/public/v1/projects'
      fullPath: '/api/public/v1/projects'
      preLoaderRoute: typeof ApiPublicV1ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/users': {
      id: '/api/public/v1/users'
      path: '/api/public/v1/users'
      fullPath: '/api/public/v1/users'
      preLoaderRoute: typeof ApiPublicV1UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/projects/$id': {
      id: '/api/public/v1/projects/$id'
      path: '/$id'
      fullPath: '/api/public/v1/projects/$id'
      preLoaderRoute: typeof ApiPublicV1ProjectsIdRouteImport
      parentRoute: typeof ApiPublicV1ProjectsRoute
    }
  }
}

interface DashRouteChildren {
  DashArchivedRoute: typeof DashArchivedRoute
  DashDashboardRoute: typeof DashDashboardRoute
  DashEmailsRoute: typeof DashEmailsRoute
  DashGoLiveRoute: typeof DashGoLiveRoute
  DashPlatformsRoute: typeof DashPlatformsRoute
  DashRisksRoute: typeof DashRisksRoute
  DashShopifyLtEmailsRoute: typeof DashShopifyLtEmailsRoute
  DashShopifySmeRoute: typeof DashShopifySmeRoute
  DashTenantsRoute: typeof DashTenantsRoute
  DashIndexRoute: typeof DashIndexRoute
  DashProjectsGoLiveRoute: typeof DashProjectsGoLiveRoute
  DashProjectsKanbanRoute: typeof DashProjectsKanbanRoute
  DashProjectsListRoute: typeof DashProjectsListRoute
  DashReportsSubTabRoute: typeof DashReportsSubTabRoute
  DashSettingsSubTabRoute: typeof DashSettingsSubTabRoute
  DashReportsPredefinedReportTypeRoute: typeof DashReportsPredefinedReportTypeRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashArchivedRoute: DashArchivedRoute,
  DashDashboardRoute: DashDashboardRoute,
  DashEmailsRoute: DashEmailsRoute,
  DashGoLiveRoute: DashGoLiveRoute,
  DashPlatformsRoute: DashPlatformsRoute,
  DashRisksRoute: DashRisksRoute,
  DashShopifyLtEmailsRoute: DashShopifyLtEmailsRoute,
  DashShopifySmeRoute: DashShopifySmeRoute,
  DashTenantsRoute: DashTenantsRoute,
  DashIndexRoute: DashIndexRoute,
  DashProjectsGoLiveRoute: DashProjectsGoLiveRoute,
  DashProjectsKanbanRoute: DashProjectsKanbanRoute,
  DashProjectsListRoute: DashProjectsListRoute,
  DashReportsSubTabRoute: DashReportsSubTabRoute,
  DashSettingsSubTabRoute: DashSettingsSubTabRoute,
  DashReportsPredefinedReportTypeRoute: DashReportsPredefinedReportTypeRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

interface PortalRouteChildren {
  PortalMidRoute: typeof PortalMidRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalMidRoute: PortalMidRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ApiPublicMerchantPortalDataRouteChildren {
  ApiPublicMerchantPortalDataSplatRoute: typeof ApiPublicMerchantPortalDataSplatRoute
}

const ApiPublicMerchantPortalDataRouteChildren: ApiPublicMerchantPortalDataRouteChildren =
  {
    ApiPublicMerchantPortalDataSplatRoute:
      ApiPublicMerchantPortalDataSplatRoute,
  }

const ApiPublicMerchantPortalDataRouteWithChildren =
  ApiPublicMerchantPortalDataRoute._addFileChildren(
    ApiPublicMerchantPortalDataRouteChildren,
  )

interface ApiPublicV1ProjectsRouteChildren {
  ApiPublicV1ProjectsIdRoute: typeof ApiPublicV1ProjectsIdRoute
}

const ApiPublicV1ProjectsRouteChildren: ApiPublicV1ProjectsRouteChildren = {
  ApiPublicV1ProjectsIdRoute: ApiPublicV1ProjectsIdRoute,
}

const ApiPublicV1ProjectsRouteWithChildren =
  ApiPublicV1ProjectsRoute._addFileChildren(ApiPublicV1ProjectsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashRoute: DashRouteWithChildren,
  BrdRoute: BrdRoute,
  PortalRoute: PortalRouteWithChildren,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ApiPublicAiActionsRoute: ApiPublicAiActionsRoute,
  ApiPublicAiChatRoute: ApiPublicAiChatRoute,
  ApiPublicAiFieldMappingRoute: ApiPublicAiFieldMappingRoute,
  ApiPublicAiProjectInsightsRoute: ApiPublicAiProjectInsightsRoute,
  ApiPublicApiKeysRoute: ApiPublicApiKeysRoute,
  ApiPublicAssignShopifySmeOwnerRoute: ApiPublicAssignShopifySmeOwnerRoute,
  ApiPublicBackfillShopifySmeAssignmentsRoute:
    ApiPublicBackfillShopifySmeAssignmentsRoute,
  ApiPublicBrdFormApiRoute: ApiPublicBrdFormApiRoute,
  ApiPublicCheckOverdueTasksRoute: ApiPublicCheckOverdueTasksRoute,
  ApiPublicCreateJiraTicketRoute: ApiPublicCreateJiraTicketRoute,
  ApiPublicCreateUserRoute: ApiPublicCreateUserRoute,
  ApiPublicCronRoute: ApiPublicCronRoute,
  ApiPublicDeleteUserRoute: ApiPublicDeleteUserRoute,
  ApiPublicEnrichGoliveTrackerRoute: ApiPublicEnrichGoliveTrackerRoute,
  ApiPublicFetchProjectEmailsRoute: ApiPublicFetchProjectEmailsRoute,
  ApiPublicFetchProjectJiraTicketsRoute: ApiPublicFetchProjectJiraTicketsRoute,
  ApiPublicGetProjectLinksRoute: ApiPublicGetProjectLinksRoute,
  ApiPublicJiraCreateUrlRoute: ApiPublicJiraCreateUrlRoute,
  ApiPublicKwikassistAiChatRoute: ApiPublicKwikassistAiChatRoute,
  ApiPublicMerchantPortalDataRoute:
    ApiPublicMerchantPortalDataRouteWithChildren,
  ApiPublicPollEmailsRoute: ApiPublicPollEmailsRoute,
  ApiPublicPollPlatformGoliveEmailsRoute:
    ApiPublicPollPlatformGoliveEmailsRoute,
  ApiPublicPollShopifySmeEmailsRoute: ApiPublicPollShopifySmeEmailsRoute,
  ApiPublicSandboxTestRoute: ApiPublicSandboxTestRoute,
  ApiPublicSendMovementReportRoute: ApiPublicSendMovementReportRoute,
  ApiPublicSendNotificationRoute: ApiPublicSendNotificationRoute,
  ApiPublicSendPlatformWelcomeRoute: ApiPublicSendPlatformWelcomeRoute,
  ApiPublicSendScheduledMovementReportRoute:
    ApiPublicSendScheduledMovementReportRoute,
  ApiPublicSendScheduledReportRoute: ApiPublicSendScheduledReportRoute,
  ApiPublicSendScheduledTatReportRoute: ApiPublicSendScheduledTatReportRoute,
  ApiPublicSetPasswordRoute: ApiPublicSetPasswordRoute,
  ApiPublicShopifyLtEmailCommsRoute: ApiPublicShopifyLtEmailCommsRoute,
  ApiPublicSlackStuckMerchantsDigestRoute:
    ApiPublicSlackStuckMerchantsDigestRoute,
  ApiPublicTenantIntegrationsRoute: ApiPublicTenantIntegrationsRoute,
  ApiPublicUpdateUserRoute: ApiPublicUpdateUserRoute,
  ApiPublicUploadProjectPdfRoute: ApiPublicUploadProjectPdfRoute,
  ApiPublicV1HealthRoute: ApiPublicV1HealthRoute,
  ApiPublicV1ProjectsRoute: ApiPublicV1ProjectsRouteWithChildren,
  ApiPublicV1UsersRoute: ApiPublicV1UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
